fix

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -31,28 +31,46 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+#      - name: Detect package manager
+#        id: detect-package-manager
+#        run: |
+#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+#            echo "manager=yarn" >> $GITHUB_OUTPUT
+#            echo "command=install" >> $GITHUB_OUTPUT
+#            echo "runner=yarn" >> $GITHUB_OUTPUT
+#            exit 0
+#          elif [ -f "${{ github.workspace }}/package.json" ]; then
+#            echo "manager=npm" >> $GITHUB_OUTPUT
+#            echo "command=ci" >> $GITHUB_OUTPUT
+#            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+#            exit 0
+#          else
+#            echo "Unable to determine package manager"
+#            exit 1
+#          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - uses: pnpm/action-setup@v2
+        name: Install pnpm
+        id: pnpm-install
+        with:
+          version: 7
+          run_install: false
+      - name: Get pnpm store directory
+        id: pnpm-cache
+        shell: bash
+        run: |
+          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
+      - uses: actions/cache@v3
+        name: Setup pnpm cache
+        with:
+          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
+          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-store-
       - name: Setup Pages
         uses: actions/configure-pages@v5
         with:
